# Default values for helm deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
deployment:
  containers:
    - image: pihole/pihole:latest
      ports:
        - name: dns-port
          containerPort: 53
        - name: web-port
          containerPort: 80
      volumeMounts:
        - name: pi-hole-storage
          mountPath: /etc/pihole/
        - name: dns-storage
          mountPath: /etc/dnsmasq.d/
      env:
        # after helm install run:
        # kubectl create secret generic <mysecret> -n <.Release.Name> --from-literal <key>='<value>'
        - name: TZ
          value: "America/Denver"
  volumes:
    - name: pi-hole-storage
      persistentVolumeClaim:
        claimName: pi-hole-pv-claim
      volumeName: pi-hole-volume
      size: .5Gi
      hostPath: "data/pi-hole/pihole"  # prefixed by data/, defaults to data/.Release.Name
    - name: dns-storage
      persistentVolumeClaim:
        claimName: dns-pv-claim
      volumeName: dns-volume
      size: .5Gi
      hostPath: "data/pi-hole/dnsmasq.d"  # prefixed by data/, defaults to data/.Release.Name

service:
  ports:
    - name: dns-port-name
      port: 53
      targetPort: 53
    - name: web-port-name
      port: 80
      targetPort: 80

ingress:
  enabled: true
  rules:
    - host: "pi-hole.greatdnd.world"
      http:
        paths:
          - path: /
#            pathType: Prefix  # optional
            backend:
              service:
                # defaults to release name, only ok if one rule
                name: "dns"
                port:
                  number: 80

# this is namespace bound
appRole: cluster-admin
