apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Name }}
  {{- if .Values.statefulset.labels }}
  labels:
    {{- range .Values.statefulset.labels }}
    {{ .key }}: {{ .value }}
    {{- end}}
  {{- end}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  serviceName: {{ .Release.Name }}-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      containers:
        {{- range .Values.statefulset.containers }}
        - name: {{ .name | default $.Release.Name }}
          image: {{ .image }}
          ports:
            {{- range .ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
            {{- end }}
          {{- if .volumeMounts }}
          volumeMounts:
            {{- range .volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath | quote }}
              readOnly: {{ .readOnly | default "false" }}
            {{- end }}
          {{- end }}
          env:
          {{- range .env }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .valueFrom.secretKeyRef.name }}
                  key: {{ .valueFrom.secretKeyRef.key }}
          {{- end }}
        {{- end }}
        {{- if .Values.statefulset.volumes }}
      {{- if .volumes }}
      volumes:
        {{- range .Values.statefulset.volumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .persistentVolumeClaim.claimName }}
        {{- end }}
      {{- end }}
      {{- end }}
