apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Name }}
  {{- if .Values.deployment.labels }}
  labels:
    {{- range .Values.deployment.labels }}
    {{ .key }}: {{ .value }}
    {{- end }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      {{- if .Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.deployment.imagePullSecrets }}
      {{- end }}
      serviceAccountName: {{ .Release.Name }}
      containers:
        {{- range .Values.deployment.containers }}
        - name: {{ .name | default $.Release.Name }}
          image: {{ .image }}
          ports:
            {{- range .ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
            {{- end }}
          {{- if .volumeMounts }}
          volumeMounts:
            {{- range .volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath | quote }}
              readOnly: {{ .readOnly | default "false" }}
            {{- end }}
          {{- end }}
          env:
          {{- range .env }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .valueFrom.secretKeyRef.name }}
                  key: {{ .valueFrom.secretKeyRef.key }}
          {{- end }}
        {{- end }}
      {{- if .Values.deployment.volumes }}
      volumes:
        {{- range .Values.deployment.volumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .persistentVolumeClaim.claimName }}
        {{- end }}
      {{- end }}
