apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: acme-prod
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol | default "TCP" | quote }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
---
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Name }}
  annotations:
    cert-manager.io/cluster-issuer: "acme-prod"
    acme.cert-manager.io/http01-edit-in-place: "true"
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
  {{- range .Values.ingress.rules }}
  {{- if .host }}
  - host: {{ .host }}
    http:
  {{- else }}
  - http:
  {{- end }}
      paths:
      {{- range .http.paths }}
      - path: {{ .path | default "/" | quote }}
        pathType: {{ .pathType | default "Prefix" | quote }}
        backend:
          service:
            name: {{ .backend.service.name | default $.Release.Name }}-service
            port:
              number: {{ .backend.service.port.number }}
      {{- end }}
  tls:
    - hosts:
        - {{ .host }}
      secretName: greatdnd-world-tls
  {{- end }}
{{- end }}
{{- /*}}
---
  {{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-http
  namespace: {{ .Release.Name }}
spec:
  rules:
  {{- range .Values.ingress.rules }}
  {{- if .host }}
  - host: {{ .host }}
    http:
  {{- else }}
  - http:
  {{- end }}
  paths:
  {{- range .http.paths }}
  - path: {{ .path | default "/" | quote }}
    pathType: {{ .pathType | default "Prefix" | quote }}
    backend:
      service:
        name: {{ .backend.service.name | default $.Release.Name }}-service
        port:
          number: {{ .backend.service.port.number }}
  {{- end }}
  {{- end }}
  {{- end }}

  {{- */}}