apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Name }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-admin
  namespace: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}
    namespace: {{ .Release.Name }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.appRole | default "cluster-admin" | quote }}
  apiGroup: rbac.authorization.k8s.io
