---
{{- range .Values.statefulset.volumes }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .volumeName }}
  labels:
    type: local
spec:
  capacity:
    storage: {{ .size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "data/{{ .hostPath | default $.Release.Name }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .persistentVolumeClaim.claimName }}
  namespace: {{ $.Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size }}
{{- end }}
