# Default values for foundry-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
statefulset:
  containers:
    - image: felddy/foundryvtt:release
      ports:
        - name: foundry-dev
          containerPort: 30000
      volumeMounts:
        - name: foundry-dev-storage
          mountPath: /data
      env:
      # after helm install run:
      # kubectl create secret generic login-info --from-literal username='' --from-literal password=''
        - name: FOUNDRY_USERNAME
          valueFrom:
            secretKeyRef:
              name: login-info
              key: username
        - name: FOUNDRY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: login-info
              key: password
  volumes:
    - name: foundry-dev-storage
      persistentVolumeClaim:
        claimName: foundry-dev-pv-claim
      volumeName: foundry-dev-volume
      size: 10Gi
      hostPath: ""  # prefixed by data/, defaults to data/.Release.Name

service:
  ports:
    - name: foundry-dev
      port: 30000
      targetPort: 30000

ingress:
  enabled: true
  rules:
    - host: "foundry-dev.greatdnd.world"
      http:
        paths:
          - path: /
#            pathType: Prefix  # optional
            backend:
              service:
#                name: ""  # defaults to .Release.Name, only ok if one rule
                port:
                  number: 30000

appRole: cluster-admin
