apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-staging
spec:
  acme:
    email: alexromine3@gmail.com # replace with your email
    server: https://acme-staging-v02.api.letsencrypt.org/directory # staging
    privateKeySecretRef:
      name: acme-staging
    solvers:
    - http01:
        ingress:
          class: traefik
